version: '3.1'

services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: uberflug-docker
    container_name: uberflugapp
    restart: always
    ports:
      - "3000:3000"
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: uberflug
    volumes:
      - ./docker/mongo:/data/db
